pipeline:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: https://registry.rogescus.com
      username: 
        from_secret: nexus_username
      password:
        from_secret: nexus_password
      repo: registry.rogescus.com/jancubillan/webhook
