steps:
  build:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NEXUS_USERNAME:
        from_secret: nexus_username
      NEXUS_PASSWORD:
        from_secret: nexus_password
    commands:
      - apk add --no-cache make
      - make -f Makefile.woodpecker release
    when:
      - event: [push, manual]
        branch: feat/makefile-woodpecker-integration
